name: Srejan
favicon: null
layout_spectrum: 0.74853
typography_spectrum: 0.49609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.75
  lightness: 0.24391979072242975
  saturation: 0.24893314437940717
  rhythmicContrast: 0.5
purpose: []
